

@host = https://locations-api-v2.herokuapp.com/api


GET {{host}}/locations/

###

GET {{host}}/locations/3

###

DELETE {{host}}/locations/4

###

POST {{host}}/locations/
Content-type: application/json

{
    "latitude": 0.0,
    "longitude": 180.0
}

###

PUT {{host}}/locations/160
Content-type: application/json

{
    "latitude": 22.0,
    "longitude": 112.0
}

###

PATCH {{host}}/locations/5
Content-type: application/json

{
    "latitude": 9.0,
    "longitude": 11.0
}
