GET http://localhost:8080/api/locations/

###

GET http://localhost:8080/api/locations/2

###

DELETE http://localhost:8080/api/locations/1

###

POST http://localhost:8080/api/locations/
Content-type: application/json

{
    "latitude": 0.0,
    "longitude": 180.0
}

###

PUT http://localhost:8080/api/locations/55
Content-type: application/json

{
    "latitude": 20.0,
    "longitude": 110.0
}

###

PATCH http://localhost:8080/api/locations/2
Content-type: application/json

{
    "latitude": 1.0,
    "longitude": 1.0
}
